// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhNVEoamJxQIS_5cxElH7t8lQyaN_i7E0',
    appId: '1:519983833825:web:359e295867211e04f24da0',
    messagingSenderId: '519983833825',
    projectId: 'pet-care-pcc',
    authDomain: 'pet-care-pcc.firebaseapp.com',
    storageBucket: 'pet-care-pcc.appspot.com',
    measurementId: 'G-9NDRSSSFBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0fs9TSdy9eIfCqqx--kTdOffrIBtqQJU',
    appId: '1:519983833825:android:de0c12e835bd7da8f24da0',
    messagingSenderId: '519983833825',
    projectId: 'pet-care-pcc',
    storageBucket: 'pet-care-pcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOqtmRHMyr6UTe80cURFaTOj4h1eHON1U',
    appId: '1:519983833825:ios:4a1a910ac619d771f24da0',
    messagingSenderId: '519983833825',
    projectId: 'pet-care-pcc',
    storageBucket: 'pet-care-pcc.appspot.com',
    iosBundleId: 'com.pcc.petcarecompanions',
  );

}